# Use root/example as user/password credentials
version: '3.3'

services:


  node-red:
    container_name: iot-project-node-red
    build:
      context: ./nodered/
      dockerfile: Dockerfile
    image: nodered:latest
    env_file:
      - .env
    ports:
      - "1880:1880"
    networks:
      iot-project-network:
        ipv4_address: 172.30.0.100
    volumes:
      - ./nodered/data:/data

  mosquitto:
    container_name: iot-project-mosquitto
    image: eclipse-mosquitto
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ./mosquitto/log:/mosquitto/log
    - ./mosquitto/data/:/mosquitto/data
    restart: always
    networks:
      iot-project-network:
        ipv4_address: 172.30.0.101
    ports:
    - "1883:1883" 

  influxdb:
    container_name: iot-project-influxdb
    image: influxdb:2.7.4
    env_file:
      - .env
    volumes:
    - $PWD/influxdb/data:/var/lib/influxdb2:rw
    ports:
       - 8086:8086
    networks:
       iot-project-network:
         ipv4_address: 172.30.0.103

  telegraf:
    restart: always
    container_name: iot-project-telegraf
    image: telegraf:latest
    env_file:
      - .env
    volumes:
      - $PWD/telegraf/mqtt_client.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      iot-project-network:
        ipv4_address: 172.30.0.104

  grafana:
    restart: always
    image: grafana/grafana-oss:latest
    container_name: iot-project-grafana
    volumes:
      - $PWD/grafana/data:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    networks:
      iot-project-network:
        ipv4_address: 172.30.0.105

networks:
  iot-project-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16