# Use root/example as user/password credentials
version: '3.3'

services:

  # db:
  #   image: mysql
  #   container_name: se4iot-mysql
  #   # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #   # (this is just an example, not intended to be a production configuration)
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #   ports:
  #   - "3306:3306" 
  #   volumes:
  #   - ./mysql-dump:/docker-entrypoint-initdb.d

  # adminer:
  #   image: adminer
  #   container_name: se4iot-mysql-adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
#    networks:
#      - se4iot-net

  node-red:
    container_name: iot-project-node-red
    build:
      context: ./nodered/
      dockerfile: Dockerfile
    image: nodered:latest
    environment:
      - TZ=Europe/Amsterdam
      # - MYSQLUSERNAME=root
      # - MYSQLPASSWORD=example
    ports:
      - "1880:1880"
    networks:
      iot-project-network:
        ipv4_address: 172.30.0.100
    volumes:
      - ./nodered/data:/data

  mosquitto:
    container_name: iot-project-mosquitto
    image: eclipse-mosquitto
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ./mosquitto/log:/mosquitto/log
    - ./mosquitto/data/:/mosquitto/data
    restart: always
    networks:
      iot-project-network:
        ipv4_address: 172.30.0.101
    ports:
    - "1883:1883" 

  # mycoapserver:
  #   container_name: se4iot-simplecoapserver
  #   build:
  #     context: ./coapserver/
  #     dockerfile: Dockerfile
  #   image: mycoapserver:latest
  #   networks:
  #     se4iot-network:
  #       ipv4_address: 172.30.0.102
  #   ports:
  #     - "5683:5683"

  influxdb:
    container_name: iot-project-influxdb
    image: influxdb:2.7.4
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=adminadmin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=Iot-23-24
      - DOCKER_INFLUXDB_INIT_BUCKET=Iot-project
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ardtyGcZCP_F5qJ7TG9keM6Y0rVkSS9fYNy_AJN-Wk8IQydqA6E-HieWoKm5pCZ9RKB93mK2wOLtMyRsp9vVXQ==
    volumes:
    - $PWD/influxdb/data:/var/lib/influxdb2:rw
    ports:
       - 8086:8086
    networks:
       iot-project-network:
         ipv4_address: 172.30.0.103

  telegraf:
    restart: always
    container_name: iot-project-telegraf
    image: telegraf:latest
    environment:
      #All-access token
      #- INFLUX_TOKEN=SOdZXSWMAa-BaWgNOqBSA130L_vjiBDy2jlCUzvqTQoZRUZE40hHOvizifo2xpCQCHty7MdHE_8UJQh2MBJcOQ==
      - INFLUX_TOKEN=GhJNShLep5FOz6ft4oltz9hX1MWs90cEazCCPut_Nt65Zwapm08ODZBFcRUR2CsXsWQvZ5Ts8iQ4CSS-cWrnUA==
    volumes:
      - $PWD/telegraf/mqtt_client.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      iot-project-network:
        ipv4_address: 172.30.0.104

  grafana:
    restart: always
    image: grafana/grafana-oss:latest
    container_name: iot-project-grafana
    volumes:
      - $PWD/grafana/data:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    networks:
      iot-project-network:
        ipv4_address: 172.30.0.105

networks:
  iot-project-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16